### ISSUE TITLE
fix the whitespaces!!!!! 💢 

### ISSUE THREAD

**Issue by jann-amh** [benASTRO/ApuDoingStuff#1]
@benASTRO 💢

**Comment by jann-amh** [comment]
very 💢

**Comment by jann-amh** [comment]
![grafik](https://user-images.githubusercontent.com/58480669/128348511-adacbc80-19f6-4f53-965c-d9424b34ad8d.png)

**Comment by hendriklhf** [comment]
wtf @benASTRO 💢

**Comment by hendriklhf** [comment]
@benASTRO when fix? 🙂
